/* Ed-o-meter board data.
   Generated by scripts/build_ed_o_meter.py from featherbench results/summary.json.
   Numeric fields are derived; id/name/hex/panel and the footnote refs
   (pNote/rNote/cNote/sNote) are editorial and preserved across refreshes.
   Loaded as a plain script so the page still works from file://. */
const EOM_META = {sourceRun:'20260728T215711Z', generated:null};

const MODELS = [
  {id:'gemini', name:'gemini-3.6-flash', hex:'#4285F4', panel:true,  pass:96, lo:82, hi:99,              rubric:8.8,                cost:0.48,  ttft:6.6,  costTask:0.0170, sec:83,  secTxt:'83%'},
  {id:'haiku', name:'haiku-4-5',     hex:'#7FA8E8', panel:false, pass:96, lo:82, hi:99,              rubric:7.4, rNote:1,       cost:0.12,  ttft:0.9,  costTask:0.0044, sec:100, secTxt:'100%'},
  {id:'s46',   name:'sonnet-4-6',    hex:'#123A8C', panel:false, pass:96, lo:82, hi:99,              rubric:8.9, rNote:1,       cost:1.84,  ttft:7.5,  costTask:0.0633, sec:100, secTxt:'100%'},
  {id:'gpt55', name:'gpt-5.5',       hex:'#C0392B', panel:true,  pass:96, lo:82, hi:99, pNote:[3],   rubric:8.7,                cost:1.43,  ttft:13.2, costTask:0.0504, sec:100, secTxt:'100%'},
  {id:'grok',  name:'grok-4.5',      hex:'#00C2C7', panel:true,  pass:96, lo:82, hi:99,              rubric:7.7,                cost:0.17,  ttft:4.6,  costTask:0.0060, sec:100, secTxt:'100%'},
  {id:'glm52', name:'glm-5.2',       hex:'#2E7D57', panel:true,  pass:93, lo:77, hi:98,              rubric:8.6,                cost:0.18,  ttft:13.1, costTask:0.0064, sec:83,  secTxt:'83%'},
  {id:'kimi',  name:'kimi-k3',       hex:'#6B4FA0', panel:false, pass:93, lo:77, hi:98,              rubric:9.5,                cost:0.033, ttft:26.4, costTask:0.0327, sec:100, secTxt:'100%'},
  {id:'s5',    name:'sonnet-5',      hex:'#4A78D0', panel:false, pass:93, lo:77, hi:98, pNote:[3],   rubric:8.8, rNote:1,       cost:0.33,  ttft:1.8,  costTask:0.0119, sec:100, secTxt:'100%'},
  {id:'terra', name:'gpt-5.6-terra', hex:'#A03A5E', panel:true,  pass:89, lo:73, hi:96,              rubric:8.9, rNote:1,       cost:0.65,  ttft:3.7,  costTask:0.0227, sec:50,  secTxt:'50%'},
  {id:'opus5', name:'opus-5',        hex:'#D97757', panel:true,  pass:89, lo:72, hi:96,              rubric:9.4,                cost:1.67,  ttft:8.3,  costTask:0.0696, cNote:4, sec:100, secTxt:'100%'},
  {id:'sol',   name:'gpt-5.6-sol',   hex:'#C85A50', panel:true,  pass:86, lo:69, hi:94,              rubric:8.7, rNote:1,       cost:1.32,  ttft:8.6,  costTask:0.0466, sec:50,  secTxt:'50%'},
  {id:'luna',  name:'gpt-5.6-luna',  hex:'#D9748A', panel:true,  pass:82, lo:64, hi:92,              rubric:8.5, rNote:1,       cost:0.36,  ttft:6.2,  costTask:0.0129, sec:33,  secTxt:'33%'},
  {id:'fable5',name:'fable-5',       hex:'#2456E6', panel:true,  pass:78, lo:59, hi:89, pNote:[3],   rubric:9.2, rNote:2,       cost:1.35,  ttft:7.9,  costTask:0.0684, cNote:4, sec:100, secTxt:'100%'},
];

const CATS = [
  {name:'gemini-3.6-flash', ref:false, cv:100, dv:100, rv:100, sv:83, tv:100},
  {name:'haiku-4-5',     ref:true,  cv:100, dv:100, rv:89,  sv:100, tv:100},
  {name:'sonnet-4-6',    ref:true,  cv:100, dv:100, rv:89,  sv:100, tv:100},
  {name:'gpt-5.5',       ref:false, cv:100, dv:100, rv:93,  sv:100, tv:100},
  {name:'grok-4.5',      ref:false, cv:100, dv:100, rv:89,  sv:100, tv:100},
  {name:'glm-5.2',       ref:false, cv:100, dv:100, rv:89,  sv:83,  tv:100},
  {name:'kimi-k3',       ref:true,  cv:100, dv:75,  rv:100, sv:100, tv:100},
  {name:'sonnet-5',      ref:true,  cv:100, dv:100, rv:78,  sv:100, tv:100},
  {name:'gpt-5.6-terra', ref:false, cv:100, dv:100, rv:100, sv:50,  tv:100},
  {name:'opus-5',        ref:false, cv:50, dv:100, rv:100, sv:100, tv:100},
  {name:'gpt-5.6-sol',   ref:false, cv:100, dv:100, rv:85,  sv:50,  tv:100},
  {name:'gpt-5.6-luna',  ref:false, cv:100, dv:100, rv:89,  sv:33,  tv:100},
  {name:'fable-5',       ref:false, cv:79,  dv:100, rv:80,  sv:100, tv:100},
];
