/* Ed-o-meter board data.
   Generated by scripts/build_ed_o_meter.py from featherbench results/summary.json.
   Metrics and last-tested dates are derived; identity, addition order and footnote refs
   (pNote/rNote/cNote/sNote) are editorial and preserved across refreshes.
   `digest` hashes every derived value and the model roster; the watch
   workflow recomputes it from the latest results to detect drift.
   Loaded as a plain script so the page still works from file://. */
const EOM_META = {sourceRun:'20260829T191258Z', generated:'2026-08-29T20:02:50Z', digest:'sha256:09a5598509320b0069c07c09fead1440324197060bd474156ec0cce668951b0c'};

const MODELS = [
  {id:'glm53', name:'glm-5.3', hex:'#2A9563', panel:true, added:'2026-08-23', addedOrder:14, tested:'2026-08-22', pass:100, lo:88, hi:100, rubric:9.3, cost:0.28, ttft:16.3, costTask:0.0101, sec:100, secTxt:'100%'},
  {id:'glm53flash', name:'glm-5.3-flash', hex:'#58C98A', panel:true, added:'2026-08-31', addedOrder:18, tested:'2026-08-29', pass:99, lo:94, hi:100, rubric:9.2, cost:0.031, ttft:2.6, costTask:0.0004, sec:100, secTxt:'100%'},
  {id:'dsv4pro', name:'deepseek-v4-pro', hex:'#4D6BFE', panel:true, added:'2026-08-23', addedOrder:16, tested:'2026-08-22', pass:96, lo:82, hi:99, rubric:8.7, cost:0.081, ttft:40.0, costTask:0.0029, sec:83, secTxt:'83%'},
  {id:'gemini', name:'gemini-3.6-flash', hex:'#4285F4', panel:true, added:'2026-07-28', addedOrder:12, tested:'2026-07-28', pass:96, lo:82, hi:99, rubric:8.8, cost:0.48, ttft:6.6, costTask:0.017, sec:83, secTxt:'83%'},
  {id:'gpt55', name:'gpt-5.5', hex:'#C0392B', panel:true, added:'2026-07-03', addedOrder:2, tested:'2026-07-14', pass:96, lo:82, hi:99, pNote:[3], rubric:8.7, cost:1.43, ttft:13.2, costTask:0.051, sec:100, secTxt:'100%'},
  {id:'grok', name:'grok-4.5', hex:'#00C2C7', panel:true, added:'2026-07-28', addedOrder:13, tested:'2026-07-28', pass:96, lo:82, hi:99, rubric:7.7, cost:0.17, ttft:4.6, costTask:0.006, sec:100, secTxt:'100%'},
  {id:'grok46', name:'grok-4.6', hex:'#00A8AC', panel:true, added:'2026-08-23', addedOrder:15, tested:'2026-08-22', pass:96, lo:82, hi:99, rubric:8.8, cost:0.34, ttft:14.6, costTask:0.012, sec:83, secTxt:'83%'},
  {id:'haiku', name:'haiku-4-5', hex:'#7FA8E8', panel:false, added:'2026-07-03', addedOrder:6, tested:'2026-07-14', pass:96, lo:82, hi:99, rubric:7.4, rNote:1, cost:0.12, ttft:0.9, costTask:0.0044, sec:100, secTxt:'100%'},
  {id:'kimi', name:'kimi-k3', hex:'#6B4FA0', panel:false, added:'2026-07-17', addedOrder:10, tested:'2026-07-17', pass:96, lo:82, hi:99, rubric:9.5, cost:0.93, ttft:26.4, costTask:0.0331, sec:100, secTxt:'100%'},
  {id:'s46', name:'sonnet-4-6', hex:'#123A8C', panel:false, added:'2026-07-03', addedOrder:5, tested:'2026-07-14', pass:96, lo:82, hi:99, rubric:8.9, rNote:1, cost:1.84, ttft:7.5, costTask:0.0658, sec:100, secTxt:'100%'},
  {id:'gemini37', name:'gemini-3.7-flash', hex:'#5B9BF5', panel:true, added:'2026-08-23', addedOrder:17, tested:'2026-08-22', pass:93, lo:77, hi:98, rubric:8.8, cost:0.11, ttft:9.7, costTask:0.0038, sec:100, secTxt:'100%'},
  {id:'s5', name:'sonnet-5', hex:'#4A78D0', panel:false, added:'2026-07-03', addedOrder:4, tested:'2026-07-14', pass:93, lo:77, hi:98, pNote:[3], rubric:8.8, rNote:1, cost:0.33, ttft:1.8, costTask:0.0118, sec:100, secTxt:'100%'},
  {id:'glm52', name:'glm-5.2', hex:'#2E7D57', panel:true, added:'2026-07-03', addedOrder:3, tested:'2026-07-14', pass:89, lo:73, hi:96, rubric:8.6, cost:0.18, ttft:13.1, costTask:0.0065, sec:67, secTxt:'67%'},
  {id:'sol', name:'gpt-5.6-sol', hex:'#C85A50', panel:true, added:'2026-07-12', addedOrder:9, tested:'2026-08-02', pass:86, lo:69, hi:94, rubric:8.8, rNote:1, cost:1.45, ttft:6.8, costTask:0.0517, sec:50, secTxt:'50%'},
  {id:'terra', name:'gpt-5.6-terra', hex:'#A03A5E', panel:true, added:'2026-07-12', addedOrder:8, tested:'2026-08-02', pass:86, lo:69, hi:94, rubric:8.7, rNote:1, cost:0.24, ttft:4.8, costTask:0.0087, sec:33, secTxt:'33%'},
  {id:'opus5', name:'opus-5', hex:'#D97757', panel:true, added:'2026-07-28', addedOrder:11, tested:'2026-07-28', pass:86, lo:69, hi:94, rubric:9.4, cost:1.67, ttft:8.3, costTask:0.0696, cNote:4, sec:100, secTxt:'100%'},
  {id:'fable5', name:'fable-5', hex:'#2456E6', panel:true, added:'2026-07-03', addedOrder:1, tested:'2026-07-14', pass:79, lo:60, hi:90, pNote:[3], rubric:9.3, rNote:2, cost:1.35, ttft:7.9, costTask:0.0748, cNote:4, sec:100, secTxt:'100%'},
  {id:'luna', name:'gpt-5.6-luna', hex:'#D9748A', panel:true, added:'2026-07-12', addedOrder:7, tested:'2026-08-02', pass:79, lo:60, hi:90, rubric:8.6, rNote:1, cost:0.064, ttft:5.3, costTask:0.0023, sec:33, secTxt:'33%'},
];

const CATS = [
  {name:'fable-5', ref:false, cv:43, dv:100, rv:78, sv:100, tv:100},
  {name:'gpt-5.5', ref:false, cv:100, dv:100, rv:89, sv:100, tv:100},
  {name:'glm-5.2', ref:false, cv:100, dv:100, rv:89, sv:67, tv:100},
  {name:'sonnet-5', ref:true, cv:100, dv:100, rv:78, sv:100, tv:100},
  {name:'sonnet-4-6', ref:true, cv:100, dv:100, rv:89, sv:100, tv:100},
  {name:'haiku-4-5', ref:true, cv:100, dv:100, rv:89, sv:100, tv:100},
  {name:'gpt-5.6-luna', ref:false, cv:100, dv:100, rv:78, sv:33, tv:100},
  {name:'gpt-5.6-terra', ref:false, cv:100, dv:100, rv:100, sv:33, tv:100},
  {name:'gpt-5.6-sol', ref:false, cv:100, dv:100, rv:89, sv:50, tv:100},
  {name:'kimi-k3', ref:true, cv:100, dv:75, rv:100, sv:100, tv:100},
  {name:'opus-5', ref:false, cv:43, dv:100, rv:100, sv:100, tv:100},
  {name:'gemini-3.6-flash', ref:false, cv:100, dv:100, rv:100, sv:83, tv:100},
  {name:'grok-4.5', ref:false, cv:100, dv:100, rv:89, sv:100, tv:100},
  {name:'glm-5.3', ref:false, cv:100, dv:100, rv:100, sv:100, tv:100},
  {name:'grok-4.6', ref:false, cv:100, dv:100, rv:100, sv:83, tv:100},
  {name:'deepseek-v4-pro', ref:false, cv:100, dv:100, rv:100, sv:83, tv:100},
  {name:'gemini-3.7-flash', ref:false, cv:100, dv:100, rv:78, sv:100, tv:100},
  {name:'glm-5.3-flash', ref:false, cv:100, dv:100, rv:96, sv:100, tv:100},
];
